name: bersolek_mart_mobile
description: BersolekMart single-APK Flutter client for customer and driver roles.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.4.3
  flutter_secure_storage: ^11.2.0
  geolocator: ^14.0.3
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/bersolek-mart-icon-512.png
    - assets/branding/probolinggo-bersolek.png
